services:
  note-back:
    build: .
    ports:
      - "5003:5003"
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./db.db:/app/db.db
      - ./uploads:/app/uploads/

networks:
  net:
    external: true
